// server/ssr/demo/vue-ssr/src/components/Foo.vue
<template>
  <div>
    Foo
    <button @click="clickMe">点击 {{this.$store.state.num}}</button>
    <p>{{this.$store.state.name}}</p>
  </div>
</template>

<style scoped>
</style>

<script>
export default {
  mounted() {
    // 服务端没有 mounted 钩子
    // 路由切换时，调用 mounted 采用前端渲染
    this.$store.dispatch('fetchName', { name: 'name-by-mount' })
  },
  asyncData({ dispatch } /* store */) {
    // 相当于 react getInitialProps
    return dispatch('fetchName', { name: 'name-by-asyncData' }) // 第一次服务端调，模拟延迟请求数据
  },
  methods: {
    clickMe() {
      const { dispatch, state } = this.$store
      dispatch('changeNum')
      dispatch('fetchName', {
        name: `eventName-${state.num}`,
      })
      console.log('click a button')
    },
  },
}
</script>

// server/ssr/demo/react-ssr/src/components/Foo.tsx
import React from 'react'
import { observer, inject } from 'mobx-react'
import initializeStore, { Store } from '../store'

interface FooProps {
  store: Store
}

const Foo = ({ store }: FooProps) => {
  const handleClick = () => {
    store.changeNum()
    store.fetchName()
  }

  return (
    <div>
      Foo
      <button onClick={handleClick}>{`点击 ${store.num}`}</button>
      <p>{store.name}</p>
    </div>
  )
}

Foo.getInitialProps = async _ctx => {
  // console.log(ctx)
  const store = initializeStore()
  await store.fetchName()
  return store.toJSON()
}

export default inject('store')(observer(Foo))
